-- 출시 알림 신청(waitlist) 테이블
-- Supabase 대시보드 → SQL Editor에 붙여넣고 실행하세요.
-- 원인: ResultPage.jsx의 supabase.from("waitlist").insert(...) 대상 테이블이 없어
--       PGRST205(Could not find the table 'public.waitlist') 404 오류 발생.

create table if not exists public.waitlist (
  id           bigint generated by default as identity primary key,
  contact      text not null,
  contact_type text not null check (contact_type in ('email', 'phone')),
  beer_name    text,
  created_at   timestamptz not null default now()
);

-- RLS 활성화 (익명 사용자의 무제한 읽기는 막고, 신청 insert만 허용)
alter table public.waitlist enable row level security;

-- 익명(anon) 사용자가 신청을 추가(insert)할 수 있도록 허용
drop policy if exists "anon can insert waitlist" on public.waitlist;
create policy "anon can insert waitlist"
  on public.waitlist
  for insert
  to anon
  with check (true);

-- 테이블 권한 부여 (SQL로 만든 테이블은 RLS 정책만으론 부족, GRANT도 필요)
-- insert만 부여 → 익명 사용자는 신청만 가능, 조회 불가(개인정보 보호)
grant insert on public.waitlist to anon;

-- 읽기/수정/삭제 정책·권한은 부여하지 않음 → 익명 사용자는 신청만 가능, 조회 불가
